#!/bin/bash

if [[ $PWD != $WORK_TOP/dv/common/lib_tb/addr_trans_mgr ]]; then
  echo "ERROR: must execute script in $WORK_TOP/dv/common/lib_tb/addr_trans_mgr dir"
  exit 1
fi

if [[ ! -d build ]]; then
  mkdir build
fi

cp addr_trans_mgr_pkg.sv build/.

cp $WORK_TOP/dv/common/lib_tb/sv_assert_pkg.sv $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/sv_assert_pkg.sv

/scratch3/anippuleti/ws/nan2_v2.2/hw/dv/scripts/node_modules/.bin/prep -p $WORK_TOP/../test_projects/fsys_v3.0_configs/simple_config1AchlParams.json -t $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/ncore_config_info.svh -o $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/ncore_config_info.svh
/scratch3/anippuleti/ws/nan2_v2.2/hw/dv/scripts/node_modules/.bin/prep -p $WORK_TOP/../test_projects/fsys_v3.0_configs/simple_config1AchlParams.json -t $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/memregions_per_ig.svh -o $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/memregions_per_ig.svh
/scratch3/anippuleti/ws/nan2_v2.2/hw/dv/scripts/node_modules/.bin/prep -p $WORK_TOP/../test_projects/fsys_v3.0_configs/simple_config1AchlParams.json -t $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/memregions_info.svh -o $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/memregions_info.svh
/scratch3/anippuleti/ws/nan2_v2.2/hw/dv/scripts/node_modules/.bin/prep -p $WORK_TOP/../test_projects/fsys_v3.0_configs/simple_config1AchlParams.json -t $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/select_bits.svh -o $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/select_bits.svh
/scratch3/anippuleti/ws/nan2_v2.2/hw/dv/scripts/node_modules/.bin/prep -p $WORK_TOP/../test_projects/fsys_v3.0_configs/simple_config1AchlParams.json -t $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/addr_trans_mgr.svh -o $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/addr_trans_mgr.svh

cd build/

mkdir -p exe
cd exe

vlog -sv -mfcu -64 -timescale=1ps/1ps +incdir+/engr/dev/tools/mentor/questa_10.6c_1/questasim/verilog_src/uvm-1.1d/src /engr/dev/tools/mentor/questa_10.6c_1/questasim/verilog_src/uvm-1.1d/src/uvm.sv +define+QUESTA +define+SVT_UVM_TECHNOLOGY /engr/dev/tools/mentor/questa_10.6c_1/questasim/verilog_src/uvm-1.1d/src/dpi/uvm_dpi.cc -printinfilenames -writetoplevels toplevels.f -stats=perf,verbose -warning 2367 -permissive -svext=ias,idcl,iddp +define+UVM_PACKER_MAX_BYTES=1500000 +define+UVM_DISABLE_AUTO_ITEM_RECORDING +define+UVM_USE_CALLBACKS_OBJECTION_FOR_TEST_DONE -f ../../vcs.flist -l compile.log 

if [ "$?" != "0" ]; then
  echo "ERROR: COMPILE FAILED"
  exit 1
fi

vopt  -inlineFactor=1024 -64 -debug -f toplevels.f -o top_opt -stats=perf,verbose -svext=ias,idcl,iddp -permissive -l mti_vopt.log +designfile +acc=r +noacc+tb_top.
  
if [ "$?" != "0" ]; then
  echo "ERROR: ELABORATION FAILED"
  exit 1
fi

mkdir -p ../run
cd ../run

cat << EOF > dofile
set PrefMain(LinePrefix) {}; run -a; quit -f
EOF

#vsim  -batch -64 +ntb_random_seed=57281136 +UVM_VERBOSITY=UVM_NONE +UVM_MAX_QUIT_COUNT=1 -lib $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/exe/work top_opt -L $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/exe/work -do dofile -stats=perf,verbose -solvefaildebug -permissive -l vcs1.log -permit_unmatched_virtual_intf -warning 3829,8604,12003,12023,3008,3009 +nowarn3829 +nowarn8233 -uvmcontrol=none -modelsimini /engr/dev/tools/script/modelsim.ini -novopt -sv_seed 57281136 -qwavedb=+signal +test1

vsim  -batch -64 +ntb_random_seed=92512 +UVM_VERBOSITY=UVM_NONE +UVM_MAX_QUIT_COUNT=1 -lib $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/exe/work top_opt -L $WORK_TOP/dv/common/lib_tb/addr_trans_mgr/build/exe/work -do dofile -stats=perf,verbose -solvefaildebug -permissive -l vcs2.log -permit_unmatched_virtual_intf -warning 3829,8604,12003,12023,3008,3009 +nowarn3829 +nowarn8233 -uvmcontrol=none -modelsimini /engr/dev/tools/script/modelsim.ini -novopt -sv_seed 57281136 -qwavedb=+signal +test2


