#!/bin/bash -fx
if [ -z $WORK_TOP ]; 
then
    echo "WORK_TOP is not set"
    exit 1
fi

export ARTERISD_LICENSE_FILE=5281@lic-node0.arteris.com
export PATH="/engr/prerelease/maestro/Ncore_3.6.4-10473/bin:/engr/prerelease/maestro/Ncore_3.6.4-10473/maestro-server:${PATH}"
export MAESTRO_TCLLIB=/engr/prerelease/maestro/Ncore_3.6.4-10473/maestro-doc/examples/tcllib

source $WORK_TOP/dv/scripts/setup_ncore364_Rel_repos
