#!/bin/bash -fx
if [ -z $WORK_TOP ]; 
then
    echo "WORK_TOP is not set"
    exit 1
fi

export ARTERISD_LICENSE_FILE=5281@lic-node0.arteris.com
export PATH="/engr/prerelease/maestro/Ncore_3.6.4.2-10505/bin:/engr/prerelease/maestro/Ncore_3.6.4.2-10505/maestro-server:${PATH}"
export MAESTRO_TCLLIB=/engr/prerelease/maestro/Ncore_3.6.4.2-10505/maestro-doc/examples/tcllib

source $WORK_TOP/dv/scripts/setup_ncore3642_Rel_repos
