#!/bin/csh

set TOTAL = `grep -RI "node" $WORK_TOP/dv/dce/tb/testlist | grep -v "\-t" | grep -v "#" | wc -l`
set UNIT = `grep -RI "node" $WORK_TOP/dv/dce/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $4}'`
set NAME = `grep -RI "node" $WORK_TOP/dv/dce/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $13}'`
set CONFIG = `grep -RI "node" $WORK_TOP/dv/dce/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $11}'`

make clean

if ($1 != "run_only") then

rm -rf testlist
touch testlist

@ i = 1
while ($i <= $TOTAL)

    echo "node ../../../dv/scripts/rsim.js -m -a -e $UNIT[$i] -c -n $NAME[$i] -d RTL_DUT,INHOUSE_AXI,ASSERT_ON,DUMP_ON,V1 -r -C $CONFIG[$i]" >> testlist
    @ i++

end

 tclsh ../../../dv/scripts/par_run.tcl -m 3 -e . -f testlist

endif

if ($1 != "compile_only") then

@ i = 1
while ($i <= $TOTAL)

    make spyglass NAME=$NAME[$i] FILE=../../../../debug/$UNIT[$i]/$NAME[$i]/rtl/\*dce0.v FILE2=../../../../debug/$UNIT[$i]/$NAME[$i]/memory/\*.v WAIVER=../../../../rtl/top/lint/scripts/waivers.swl
    @ i++

end

endif

rm -rf lint_dce.js
touch lint_dce.js

echo "'use strict';" >> lint_dce.js
echo "var exec = require('child_process').exec," >> lint_dce.js
echo "expect = require('chai').expect;" >> lint_dce.js
echo "describe('DCE Lint Report', function () {" >> lint_dce.js

@ i = 1
while ($i <= $TOTAL)

    echo "it('DCE Lint $NAME[$i]', function (done) {" >> lint_dce.js
    echo "exec('grep -RI "\"Error \"" rtl/dce/lint/lint.$NAME[$i]/lint/consolidated_reports/lint_lint_rtl/moresimple.rpt | wc -l', function (e, sto1, ste1) {" >> lint_dce.js
    echo "expect(sto1).to.equal('0\\n');" >> lint_dce.js
    echo "done();" >> lint_dce.js
    echo "});" >> lint_dce.js
    echo "});" >> lint_dce.js
    @ i++

end

echo "});" >> lint_dce.js
