#!/bin/csh

rm -rf ../../../debug/dmi/syn
node ../../../dv/scripts/rsim.js -m -e dmi -ad RTL_DUT -s ../../../dv/common/config/dmi/dmi_config1AchlParams.json -n syn
make clean
make dc TCL=dmi FILELIST=../../../../debug/dmi/syn/rtl/top.f TECHNODE=CLN16FFPLUS LIBRARY=tcbn16ffplusglbwp16p90 REVISION=100a FFCORNER=ffgnp0p88vm40c SSCORNER=ssgnp0p72v125c WIRELOAD=topo SCAN=no COMPILE=yes PERIOD=0.800

