#!/bin/csh

rm -rf ../../../debug/dmi/syn
node ../../../dv/scripts/rsim.js -m -e dmi -ad RTL_DUT -s ../../../dv/common/config/sw/evalConfigAchlParams.js -n syn
make clean
make dc TCL=dmi FILELIST=../../../../debug/dmi/syn/rtl/top.f TECHNODE=CLN28HPM LIBRARY=tcbn28hpmbwp35 REVISION=120a FFCORNER=ff0p88vm40c SSCORNER=ss0p72v125c WIRELOAD=ZeroWireload SCAN=no COMPILE=yes PERIOD=0.800

