//==================================================
// This file contains the Excluded objects
// Generated By User: kavish
// Format Version: 2
// Date: Tue Mar  4 12:44:42 2025
// ExclMode: default
//==================================================
CHECKSUM: "3798750652 750688352"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
		bins {{"CMD_RD_VLD","CMD_RD_NOT_SHD","CMD_RD_CLN"},{"CHI_B_AIU"},{"MrdRdClnWS"}}
	coveritem "cx_stash_reads"
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_absent"}}
