//==================================================
// This file contains the Excluded objects
// Generated By User: anippuleti
// Format Version: 2
// Date: Tue May 23 10:53:16 2017
// ExclMode: default
//==================================================
CHECKSUM: "1572220182 2550001255"
covergroup dce0_env_pkg::dce_coverage::updReqHitInCoarseRep
CHECKSUM: "1700663319 196160825"
covergroup dce0_env_pkg::dce_coverage::updReqDrpInCoarseRep
CHECKSUM: "2537491489 3878713977"
covergroup dce0_env_pkg::dce_coverage::mrd_credit_cov
	coveritem "mrd_credit_cov_cc"
		bins {{auto[0]}, {"dmi_ids[0]","dmi_ids[1]","dmi_ids[2]"}}
CHECKSUM: "2760614058 3601160190"
covergroup dce0_env_pkg::dce_coverage::pvFilterInterestingCombinations
CHECKSUM: "3272813133 2628399191"
covergroup dce0_env_pkg::dce_coverage::dir_rsp_cov
	coveritem "dir_rsp_slv"
	coveritem "dir_rsp_olv"
		bins "olv_02", "olv_04", "olv_08", "olv_40", "olv_80"
CHECKSUM: "333629975 2396341738"
covergroup dce0_env_pkg::dce_coverage::upd_req_cov
	coveritem "SFIPrivAIUID"
		bins "aiu_ids[6]"
CHECKSUM: "3387320937 1560411068"
covergroup dce0_env_pkg::dce_coverage::olvSlvForGivenCachingAgent
CHECKSUM: "3620113461 3758816610"
covergroup dce0_env_pkg::dce_coverage::eosFilterInterestingCombinations
CHECKSUM: "913579473 630174312"
covergroup dce0_env_pkg::dce_coverage::cln_str_req_cov
	coveritem "SFIPrivAIUID"
		bins "aiu_ids[0]", "aiu_ids[1]", "aiu_ids[2]", "aiu_ids[3]"
