//==================================================
// This file contains the Excluded objects
// Generated By User: kavish
// Format Version: 2
// Date: Tue Mar  4 12:34:03 2025
// ExclMode: default
//==================================================
CHECKSUM: "2459369734 3655004724"
covergroup unified_prog::dce_coverage::cg_back_to_back_allocs

CHECKSUM: "3070394733 773345081"
covergroup unified_prog::dce_coverage::cg_back_to_back_non_allocs

CHECKSUM: "4045546441 3279415978"
covergroup unified_prog::dce_coverage::cg_rtyrsp_sf_0

CHECKSUM: "3167606295 3218958213"
covergroup unified_prog::dce_coverage::cg_rtyrsp_sf_1

CHECKSUM: "1546111352 1114470356"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cp_attid"
		bins "attid_1"
CHECKSUM: "3757273045 1813991879"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_rb_message_order"
		bins "rbrsv_rbrsvrsp_rbrls_rbrlsrsp"
	coveritem "cp_smi_message_order"
		bins "rbrsv_snpreq_snprsp_rbrls"
		bins "snpreq_rbrsv_snprsp_rbrls"
CHECKSUM: "1683873670 3049682055"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
		bins {{"CMD_RD_VLD"},{"IO_CACHE_AIU","CHI_B_AIU"},{"MrdRdClnWS"}}
		bins {{"CMD_RD_NOT_SHD","CMD_RD_CLN"},{"CHI_B_AIU"},{"MrdRdClnWS"}}
	coveritem "cx_stash_reads"
		bins {{"clnws_shd"},{"CHI_B_AIU"},{"dm_hit_trgt_as_owner_and_other_sharers_present"}}
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU","CHI_B_AIU"},{"dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_absent"}}
CHECKSUM: "3344342927 3400162805"
covergroup unified_prog::dce_coverage::cg_scm_state
	coveritem "cp_counter_state"
		bins "Negative"
	coveritem "cx_dmi_counter_state"
		bins {{"dmi_9","dmi_8"},{"Negative"}}
		bins {{"dmi_7"},{"Negative"}}
		bins {{"dmi_7"},{"Empty"}}
CHECKSUM: "1546111352 3295238366"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cp_attid"
		bins "attid_1"
CHECKSUM: "1546111352 1451285638"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cp_attid"
		bins "attid_1"
CHECKSUM: "3757273045 2666334072"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_rb_message_order"
		bins "rbrsv_rbrsvrsp_rbrls_rbrlsrsp"
CHECKSUM: "3757273045 3888271120"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_rb_message_order"
		bins "rbrsv_rbrsvrsp_rbrls_rbrlsrsp"
CHECKSUM: "3757273045 2666334072"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_smi_message_order"
		bins "rbrsv_snpreq_snprsp_rbrls"
CHECKSUM: "3757273045 3888271120"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_smi_message_order"
		bins "rbrsv_snpreq_snprsp_rbrls"
CHECKSUM: "3757273045 2666334072"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_smi_message_order"
		bins "snpreq_rbrsv_snprsp_rbrls"
CHECKSUM: "3757273045 3888271120"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_smi_message_order"
		bins "snpreq_rbrsv_snprsp_rbrls"
