#!/bin/csh

rm -rf ../../../debug/aiu/syn
node ../../../dv/scripts/rsim.js -m -e aiu -ad RTL_DUT -s ../../../dv/common/config/aiu/aiu_config1AchlParams.js -n syn
make clean
make dc TCL=aiu FILELIST=../../../../debug/aiu/syn/rtl/top.f TECHNODE=CLN16FFPLUS LIBRARY=tcbn16ffplusglbwp16p90 REVISION=100a FFCORNER=ffgnp0p88vm40c SSCORNER=ssgnp0p72v125c WIRELOAD=topo SCAN=no COMPILE=yes PERIOD=0.800

