#!/bin/csh

set TOTAL = `grep -RI "node" $WORK_TOP/dv/sub_sys/tb/testlist | grep -v "\-t" | grep -v "#" | wc -l`
set UNIT = `grep -RI "node" $WORK_TOP/dv/sub_sys/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $4}'`
set NAME = `grep -RI "node" $WORK_TOP/dv/sub_sys/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $12}'`
set CONFIG = `grep -RI "node" $WORK_TOP/dv/sub_sys/tb/testlist | grep -v "\-t" | grep -v "#" | awk '{print $14}'`

make clean

if ($1 != "run_only") then

rm -rf testlist
touch testlist

@ i = 1
while ($i <= $TOTAL)

    echo "node ../../../dv/scripts/rsim.js -m -a -e $UNIT[$i] -c -n $NAME[$i] -d RTL_DUT,INHOUSE_AXI,ASSERT_ON,DUMP_ON,V1 -r -C $CONFIG[$i]" >> testlist
    @ i++

end

tclsh ../../../dv/scripts/par_run.tcl -m 3 -e . -f testlist

endif

if ($1 != "compile_only") then

@ i = 1
while ($i <= $TOTAL)

    make spyglass NAME=$NAME[$i] FILE=../../../../debug/$UNIT[$i]/$NAME[$i]/rtl/\*.v WAIVER=../scripts/waivers.swl
    @ i++

end

endif

rm -rf lint_sub_sys.js
touch lint_sub_sys.js

echo "'use strict';" >> lint_sub_sys.js
echo "var exec = require('child_process').exec," >> lint_sub_sys.js
echo "expect = require('chai').expect;" >> lint_sub_sys.js
echo "describe('Subsystem Lint Report', function () {" >> lint_sub_sys.js

@ i = 1
while ($i <= $TOTAL)

    echo "it('Subsystem Lint $NAME[$i]', function (done) {" >> lint_sub_sys.js
    echo "exec('grep -RI "\"Error \"" rtl/top/lint/lint.$NAME[$i]/lint/consolidated_reports/lint_lint_rtl/moresimple.rpt | wc -l', function (e, sto1, ste1) {" >> lint_sub_sys.js
    echo "expect(sto1).to.equal('0\\n');" >> lint_sub_sys.js
    echo "done();" >> lint_sub_sys.js
    echo "});" >> lint_sub_sys.js
    echo "});" >> lint_sub_sys.js
    @ i++

end

echo "});" >> lint_sub_sys.js
