//==================================================
// This file contains the Excluded objects
// Generated By User: skumar
// Format Version: 2
// Date: Tue Mar  4 14:55:20 2025
// ExclMode: default
//==================================================
CHECKSUM: "3757273045 3888271120"
ANNOTATION: "Refer CONC-16556: Kavish's comment on Feb 24, 2025
Refer CONC-16555"
covergroup unified_prog::dce_coverage::cg_message_timing

CHECKSUM: "1754736694 3988824410"
covergroup unified_prog::dce_coverage::cg_recall_qos

CHECKSUM: "1507586890 1735696314"
ANNOTATION: "As per Kavish: This is valid only when nAttCtrlEntries < nWays. 
Here nAttCtrlEntries=16 and SF[1].nWays=16"
covergroup unified_prog::dce_coverage::cg_rtyrsp_sf_1

CHECKSUM: "3904807213 716991629"
covergroup unified_prog::dce_coverage::cg_sf_1

CHECKSUM: "760161825 3477416923"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cp_attid"
	coveritem "cx_lkprsp_wrunqs_awunique"
CHECKSUM: "760161825 3477416923"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cx_non_stash_cmdtype_iid_type"
		ANNOTATION: "Illegal Bin"
		bins {{"CMD_WR_CLN_FULL"},{"ACE_AIU"}}
CHECKSUM: "1683873670 2083366706"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
		ANNOTATION: "Refer CONC-16555: Unreachable."
		bins {{"CMD_RD_VLD","CMD_RD_NOT_SHD","CMD_RD_CLN"},{"CHI_B_AIU"},{"MrdRdClnWS"}}
	coveritem "cx_stash_reads"
		ANNOTATION: "Refer CONC-16555: Kavish's comments on Mar 04, 2025"
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_present_other_sharers_present"}}
		ANNOTATION: "Refer CONC-16555: Kavish's comments on Mar 04, 2025"
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_present_other_sharers_absent"}}
		ANNOTATION: "Refer CONC-16555: Kavish's comments on Mar 04, 2025"
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_absent"}}
		ANNOTATION: "Refer CONC-16555: Kavish's comments on Mar 04, 2025"
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_present"}}
