//==================================================
// This file contains the Excluded objects
// Generated By User: skumar
// Format Version: 2
// Date: Tue Mar  4 13:19:10 2025
// ExclMode: default
//==================================================
CHECKSUM: "3757273045 4012289604"
ANNOTATION: "Refer CONC-16556: Kavish's comment on Feb 24, 2025 and Saad's comment"
covergroup unified_prog::dce_coverage::cg_message_timing

CHECKSUM: "3344342927 2845676179"
ANNOTATION: "Refer CONC-16556: Kavish's comment on Feb 24, 2025"
covergroup unified_prog::dce_coverage::cg_scm_state

CHECKSUM: "329011702 2861838496"
ANNOTATION: "Performance Testing is not for this release"
covergroup unified_prog::cov_perf_cnt

CHECKSUM: "1683873670 222912256"
covergroup unified_prog::dce_coverage::cg_mrd_req
	ANNOTATION: "Unreachable. See CONC-16555"
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
