//==================================================
// This file contains the Excluded objects
// Generated By User: anippuleti
// Format Version: 2
// Date: Mon May 22 13:29:56 2017
// ExclMode: default
//==================================================
CHECKSUM: "1022205077 1045808009"
covergroup dce0_env_pkg::dce_coverage::dir_commit_cov
	coveritem "dir_commit_req_attid"
		bins auto[8]-auto[15]
CHECKSUM: "1118776460 3618351553"
covergroup dce0_env_pkg::dce_coverage::rd_mrd_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1203850397 1631538530"
covergroup dce0_env_pkg::dce_coverage::maintReqinSleepBehindMaintReq
CHECKSUM: "137078037 1927634536"
covergroup dce0_env_pkg::dce_coverage::snp_credit_cov
	coveritem "snp_credit_cov_cc"
		bins {{auto[1]}, {"aiu_ids[0]"}}, {{auto[1]}, {"aiu_ids[4]"}}
CHECKSUM: "1376504449 3159770618"
covergroup dce0_env_pkg::dce_coverage::wr_snp_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1398101157 1047817483"
covergroup dce0_env_pkg::dce_coverage::cln_snp_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1414623798 1002563451"
covergroup dce0_env_pkg::dce_coverage::wr_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1506506226 3431553597"
covergroup dce0_env_pkg::dce_coverage::rd_str_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1572220182 2550001255"
covergroup dce0_env_pkg::dce_coverage::updReqHitInCoarseRep
CHECKSUM: "1686458829 4294179778"
covergroup dce0_env_pkg::dce_coverage::recallReqinSleepBehindRecallReq
CHECKSUM: "1732725252 2172797267"
covergroup dce0_env_pkg::dce_coverage::wr_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "1982974434 887759310"
covergroup dce0_env_pkg::dce_coverage::rd_mrd_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2135672401 1647801075"
covergroup dce0_env_pkg::dce_coverage::cln_snp_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2317719764 1047817483"
covergroup dce0_env_pkg::dce_coverage::wr_snp_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2674168197 4281494292"
covergroup dce0_env_pkg::dce_coverage::att_activate_sigs_cov
	coveritem "att_activate_rsp_attid"
		bins auto[8]-auto[15]
CHECKSUM: "2760614058 3601160190"
covergroup dce0_env_pkg::dce_coverage::pvFilterInterestingCombinations
CHECKSUM: "277447878 1977821699"
covergroup dce0_env_pkg::dce_coverage::wr_str_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2985186191 1002563451"
covergroup dce0_env_pkg::dce_coverage::rd_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "3103389808 1025396740"
covergroup dce0_env_pkg::dce_coverage::rd_snp_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "3272813133 2648040865"
covergroup dce0_env_pkg::dce_coverage::dir_rsp_cov
	coveritem "dir_rsp_attid"
		bins auto[8]-auto[15]
	coveritem "dir_rsp_olv"
		bins "olv_04", "olv_10"
	coveritem "dir_rsp_slv"
		bins auto[4]-auto[7], auto[12]-auto[19], auto[24]-auto[27], auto[36]-auto[39], auto[44]-auto[51], auto[56]-auto[59]
CHECKSUM: "3387320937 1560411068"
covergroup dce0_env_pkg::dce_coverage::olvSlvForGivenCachingAgent
CHECKSUM: "3445783402 2593489931"
covergroup dce0_env_pkg::dce_coverage::cmdFifoEntriesTaken
CHECKSUM: "356653452 3917258738"
covergroup dce0_env_pkg::dce_coverage::cln_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "3620113461 3758816610"
covergroup dce0_env_pkg::dce_coverage::eosFilterInterestingCombinations
CHECKSUM: "3641462241 2924714709"
covergroup dce0_env_pkg::dce_coverage::wake_req_cov
	coveritem "wake_req_attid"
		bins auto[8]-auto[15]
CHECKSUM: "587290349 3810554825"
covergroup dce0_env_pkg::dce_coverage::rd_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "913579473 3431553597"
covergroup dce0_env_pkg::dce_coverage::cln_str_req_cov
	coveritem "SFIPrivAIUID"
		bins "aiu_ids[3]"
CHECKSUM: "963750961 1002563451"
covergroup dce0_env_pkg::dce_coverage::cln_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
