//==================================================
// This file contains the Excluded objects
// Generated By User: skumar
// Format Version: 2
// Date: Tue Mar  4 11:54:00 2025
// ExclMode: default
//==================================================
CHECKSUM: "3344342927 1944960893"
ANNOTATION: "Refer CONC-16556: Kavish's comment on Feb 24, 2025"
covergroup unified_prog::dce_coverage::cg_scm_state

CHECKSUM: "3757273045 3888271120"
ANNOTATION: "Refer CONC-16556: Kavish's comment on Feb 24, 2025
Refer CONC-16555"
covergroup unified_prog::dce_coverage::cg_message_timing

CHECKSUM: "472125507 3490186472"
covergroup unified_prog::dce_coverage::cg_mrd_req
	ANNOTATION: "Ureachable. Refer CONC-16555"
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
CHECKSUM: "1546111352 3857708317"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	ANNOTATION: "Need more than 2 caching agents to hit this cross. This config has only 2 caching agents. Hence this is scenario is not reachable."
	coveritem "cx_stash_lkprsp_stashtgt_identified"
CHECKSUM: "472125507 3490186472"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_stash_reads"
		ANNOTATION: "Requires more than 2 cacheable agents. This config has only 2 such agents."
		bins {{"clnwu_unq"},{"CHI_B_AIU"},{"dm_hit_trgt_as_neither_and_owner_present_other_sharers_present"}}
		ANNOTATION: "Requires more than 2 cacheable agents. This config has only 2 such agents."
		bins {{"clnws_shd"},{"CHI_B_AIU"},{"dm_hit_trgt_as_owner_and_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_absent","dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_present"}}
		ANNOTATION: "Requires more than 2 cacheable agents. This config has only 2 such agents."
		bins {{"clnws_shd"},{"CHI_B_AIU"},{"dm_hit_trgt_as_neither_and_owner_present_other_sharers_present"}}
CHECKSUM: "2681184889 3400389258"
covergroup unified_prog::dce_coverage::cg_rbreq
	coveritem "cx_cmdtype_rbrreq"
		ANNOTATION: "Need more than 2 caching agents to hit this cross. This config has only 2 caching agents. Hence this is scenario is not reachable."
		bins {{"CMD_LD_CCH_UNQ","CMD_LD_CCH_SH"},{"rbrrsv_rbusd"}}
CHECKSUM: "1546111352 3857708317"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cp_attid"
		ANNOTATION: "Refer CONC-16555: Kavish's comment on Feb 24, 2025"
		bins "attid_40"
