//==================================================
// This file contains the Excluded objects
// Generated By User: kavish
// Format Version: 2
// Date: Tue Mar  4 15:36:00 2025
// ExclMode: default
//==================================================
CHECKSUM: "760161825 512332677"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cx_non_stash_cmdtype_iid_type"
		bins {{"CMD_WR_CLN_FULL"},{"ACE_AIU"}}
CHECKSUM: "1683873670 2603486035"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
		bins {{"CMD_RD_VLD"},{"IO_CACHE_AIU","CHI_B_AIU","ACE_AIU"},{"MrdRdClnWS"}}
		bins {{"CMD_RD_NOT_SHD","CMD_RD_CLN"},{"CHI_B_AIU","ACE_AIU"},{"MrdRdClnWS"}}
	coveritem "cx_stash_reads"
		bins {{"prefetch_unq"}-{"prefetch_shd"},{"CHI_B_AIU"},{"dm_hit_trgt_as_sharer_and_owner_present_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_absent"}}
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_owner_and_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_absent"}}
		bins {{"clnws_shd"},{"ACE_LITE_E_AIU"},{"dm_hit_trgt_as_sharer_and_owner_absent_other_sharers_absent"}}
		bins {{"clnws_shd"},{"CHI_B_AIU"},{"dm_hit_trgt_as_owner_and_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_present","dm_hit_trgt_as_sharer_and_owner_present_other_sharers_absent"}}
CHECKSUM: "3344342927 2948218657"
covergroup unified_prog::dce_coverage::cg_scm_state
	coveritem "cx_dmi_counter_state"
		bins {{"dmi_78"},{"Empty"}}
		bins {{"dmi_77"},{"Negative"}}
		bins {{"dmi_77"},{"Empty","Normal_operation"}}
		bins {{"dmi_76"},{"Empty"}}
		bins {{"dmi_75","dmi_74","dmi_73"},{"Negative"}}
		bins {{"dmi_75","dmi_74","dmi_73"},{"Empty","Normal_operation"}}
		bins {{"dmi_72"},{"Empty"}}
		bins {{"dmi_71","dmi_70","dmi_69","dmi_68","dmi_67","dmi_66","dmi_65"},{"Negative"}}
		bins {{"dmi_71","dmi_70","dmi_69","dmi_68","dmi_67","dmi_66","dmi_65"},{"Empty","Normal_operation"}}
		bins {{"dmi_64"},{"Negative"}}
		bins {{"dmi_64"},{"Empty"}}
CHECKSUM: "2533694382 1732868015"
covergroup unified_prog::plru_model#(16,20)::plru_covergroup
	coveritem "cp_plru_state_onehot"
		bins "plru_state_onehot_bin_7"
	coveritem "cp_valid_ways_onehot"
		bins "valid_way_onehot_bin_1"
		bins "valid_way_onehot_bin_0"
		bins "valid_way_onehot_bin_2"
		bins "valid_way_onehot_bin_4"
		bins "valid_way_onehot_bin_3"
		bins "valid_way_onehot_bin_6"
		bins "valid_way_onehot_bin_5"
		bins "valid_way_onehot_bin_8"
		bins "valid_way_onehot_bin_7"
		bins "valid_way_onehot_bin_10"
		bins "valid_way_onehot_bin_9"
		bins "valid_way_onehot_bin_11"
CHECKSUM: "1989512985 968844232"
covergroup unified_prog::plru_model#(256,12)::plru_covergroup
	coveritem "cp_valid_ways_onehot"
		bins "valid_way_onehot_bin_0"
