//==================================================
// This file contains the Excluded objects
// Generated By User: anippuleti
// Format Version: 2
// Date: Wed May 24 11:05:31 2017
// ExclMode: default
//==================================================
CHECKSUM: "1376504449 3458736231"
covergroup dce0_env_pkg::dce_coverage::wr_snp_req_cov
	coveritem "SFIPrivAIUID", "SFIPrivMsgType"
CHECKSUM: "1398101157 1047817483"
covergroup dce0_env_pkg::dce_coverage::cln_snp_rsp_cov
CHECKSUM: "1506506226 267978389"
covergroup dce0_env_pkg::dce_coverage::rd_str_req_cov
	coveritem "ace_exokay"
		bins auto[1]
CHECKSUM: "1521358025 2519605118"
covergroup dce0_env_pkg::dce_coverage::maintReqinSleepBehindRecallReq
CHECKSUM: "1572220182 2550001255"
covergroup dce0_env_pkg::dce_coverage::updReqHitInCoarseRep
CHECKSUM: "1686458829 4294179778"
covergroup dce0_env_pkg::dce_coverage::recallReqinSleepBehindRecallReq
CHECKSUM: "1700663319 196160825"
covergroup dce0_env_pkg::dce_coverage::updReqDrpInCoarseRep
CHECKSUM: "1982974434 937174441"
covergroup dce0_env_pkg::dce_coverage::rd_mrd_req_cov
	coveritem "SFIPrivMsgType"
		bins "mrd_inv_dtr", "mrd_vld_dtr"
CHECKSUM: "2022044062 3812341860"
covergroup dce0_env_pkg::dce_coverage::updReqHitInvVctb
CHECKSUM: "204240867 1126546080"
covergroup dce0_env_pkg::dce_coverage::updReqHitInvTf
CHECKSUM: "2135672401 287399741"
covergroup dce0_env_pkg::dce_coverage::cln_snp_req_cov
CHECKSUM: "2332449348 1623132638"
covergroup dce0_env_pkg::dce_coverage::str_rsp_cov
	coveritem "SFIPrivTR"
		bins "b11"
CHECKSUM: "2452421571 3351067037"
covergroup dce0_env_pkg::dce_coverage::recallReqinSleepBehindMaintReq
CHECKSUM: "2984428188 734053873"
covergroup dce0_env_pkg::dce_coverage::rd_snp_req_cov
	coveritem "SFIPrivAIUID", "SFIPrivMsgType"
CHECKSUM: "3387320937 1560411068"
covergroup dce0_env_pkg::dce_coverage::olvSlvForGivenCachingAgent
CHECKSUM: "37579577 3598478654"
covergroup dce0_env_pkg::dce_coverage::updReqHitVctb
CHECKSUM: "3826997429 335345680"
covergroup dce0_env_pkg::dce_coverage::coher_result_cov
	coveritem "coher_result"
		bins "so1_ss1_sd0_st0", "so0_ss1_sd0_st0"
CHECKSUM: "4001670221 2706952391"
covergroup dce0_env_pkg::dce_coverage::cohReqinSleepBehindRecallReq
CHECKSUM: "514973298 3211165312"
covergroup dce0_env_pkg::dce_coverage::exOkayPerProcId
CHECKSUM: "913579473 267978389"
covergroup dce0_env_pkg::dce_coverage::cln_str_req_cov
	coveritem "SFIPrivAIUID"
		bins "aiu_ids[0]", "aiu_ids[1]", "aiu_ids[4]", "aiu_ids[5]"
	coveritem "ace_exokay"
		bins auto[1]
	coveritem "errResult"
		bins auto[1]-auto[3]
