//==================================================
// This file contains the Excluded objects
// Generated By User: kavish
// Format Version: 2
// Date: Fri Feb 28 13:47:37 2025
// ExclMode: default
//==================================================
CHECKSUM: "1292815445 3510446868"
covergroup unified_prog::dce_coverage::cg_dm

CHECKSUM: "1754736694 3988824410"
covergroup unified_prog::dce_coverage::cg_recall_qos

CHECKSUM: "3374404847 3892793833"
covergroup unified_prog::dce_coverage::cg_dm_lkprsp
	coveritem "cx_lkprsp_wrunqs_awunique"
		bins {{"CMD_WR_UNQ_FULL"},{"dm_hit_as_sharer_and_owner_present_other_sharers_absent"},{"ACE_AIU"},{"_1_"}}
		bins {{"CMD_WR_UNQ_FULL"},{"dm_hit_as_owner_and_other_sharers_present"},{"ACE_AIU"},{"_1_"}}
		bins {{"CMD_WR_UNQ_PTL"},{"dm_hit_as_sharer_and_owner_present_other_sharers_absent"},{"ACE_AIU"},{"_1_"}}
CHECKSUM: "3757273045 3888271120"
covergroup unified_prog::dce_coverage::cg_message_timing
	coveritem "cp_rb_message_order"
		bins "rbrsv_rbrsvrsp_rbrls_rbrlsrsp"
	coveritem "cp_smi_message_order"
		bins "snpreq_rbrsv_snprsp_rbrls"
		bins "rbrsv_snpreq_snprsp_rbrls"
CHECKSUM: "896536369 3805646855"
covergroup unified_prog::dce_coverage::cg_mrd_req
	coveritem "cx_dm_hit_iid_sharer_owner_absent_sharers_absent"
		bins {{"CMD_RD_NOT_SHD","CMD_RD_CLN"},{"ACE_AIU"},{"MrdRdClnWS"}}
		bins {{"CMD_RD_VLD"},{"IO_CACHE_AIU","ACE_AIU"},{"MrdRdClnWS"}}
