//==================================================
// This file contains the Excluded objects
// Generated By User: anippuleti
// Format Version: 2
// Date: Tue May 23 15:26:08 2017
// ExclMode: default
//==================================================
CHECKSUM: "1022205077 1720530217"
covergroup dce0_env_pkg::dce_coverage::dir_commit_cov
	coveritem "dir_commit_req_attid"
		bins auto[8]-auto[15]
	coveritem "dir_commit_req_scv"
		bins auto[368:383], auto[432:447], auto[496:511], auto[752:767], auto[848:863], auto[880:895], auto[912:927], auto[1008:1023]
CHECKSUM: "1118776460 3618351553"
covergroup dce0_env_pkg::dce_coverage::rd_mrd_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "137078037 1454078954"
covergroup dce0_env_pkg::dce_coverage::snp_credit_cov
	coveritem "snp_credit_cov_cc"
		bins {{auto[0]}, {"aiu_ids[17]"}}, {{auto[1]}, {"aiu_ids[19]"}}
CHECKSUM: "1376504449 1696261021"
covergroup dce0_env_pkg::dce_coverage::wr_snp_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1398101157 1047817483"
covergroup dce0_env_pkg::dce_coverage::cln_snp_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1414623798 1002563451"
covergroup dce0_env_pkg::dce_coverage::wr_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1506506226 3506451630"
covergroup dce0_env_pkg::dce_coverage::rd_str_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "1700663319 196160825"
covergroup dce0_env_pkg::dce_coverage::updReqDrpInCoarseRep
CHECKSUM: "1732725252 2641349451"
covergroup dce0_env_pkg::dce_coverage::wr_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "1982974434 3550618751"
covergroup dce0_env_pkg::dce_coverage::rd_mrd_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2135672401 1905638868"
covergroup dce0_env_pkg::dce_coverage::cln_snp_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2317719764 1047817483"
covergroup dce0_env_pkg::dce_coverage::wr_snp_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2674168197 4281494292"
covergroup dce0_env_pkg::dce_coverage::att_activate_sigs_cov
	coveritem "att_activate_rsp_attid"
		bins auto[8]-auto[15]
CHECKSUM: "2760614058 3601160190"
covergroup dce0_env_pkg::dce_coverage::pvFilterInterestingCombinations
CHECKSUM: "277447878 1626896592"
covergroup dce0_env_pkg::dce_coverage::wr_str_req_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "2985186191 1002563451"
covergroup dce0_env_pkg::dce_coverage::rd_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
CHECKSUM: "3272813133 254916238"
covergroup dce0_env_pkg::dce_coverage::dir_rsp_cov
	coveritem "dir_rsp_attid"
		bins auto[8]-auto[15]
	coveritem "dir_rsp_slv"
		bins auto[432:447], auto[496:511], auto[752:767], auto[848:863], auto[880:895], auto[1008:1023]
CHECKSUM: "3387320937 1560411068"
covergroup dce0_env_pkg::dce_coverage::olvSlvForGivenCachingAgent
CHECKSUM: "356653452 2167504880"
covergroup dce0_env_pkg::dce_coverage::cln_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "3620113461 3758816610"
covergroup dce0_env_pkg::dce_coverage::eosFilterInterestingCombinations
CHECKSUM: "3641462241 2924714709"
covergroup dce0_env_pkg::dce_coverage::wake_req_cov
	coveritem "wake_req_attid"
		bins auto[7]-auto[15]
CHECKSUM: "587290349 2769245053"
covergroup dce0_env_pkg::dce_coverage::rd_cmd_req_cov
	coveritem "SFIPrivAIUProcID"
		bins "procIDs[5]", "procIDs[6]", "procIDs[7]"
CHECKSUM: "913579473 3506451630"
covergroup dce0_env_pkg::dce_coverage::cln_str_req_cov
	coveritem "SFITransID"
		bins auto[7]
	coveritem "SFIPrivAIUID"
		bins "aiu_ids[05]", "aiu_ids[06]", "aiu_ids[07]", "aiu_ids[08]"
CHECKSUM: "963750961 1002563451"
covergroup dce0_env_pkg::dce_coverage::cln_str_rsp_cov
	coveritem "SFITransID"
		bins auto[7]
