//==================================================
// This file contains the Excluded objects
// Generated By User: akakadiya
// Format Version: 2
// Date: Mon Apr  7 05:12:37 2025
// ExclMode: default
//==================================================
CHECKSUM: "3386872605 36304125"
ANNOTATION: " Ncore does not support Untranslated Transactions "
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_read_xact_type_armmusecsid_armmusid

CHECKSUM: "1836513804 605452477"
ANNOTATION: " Ncore does not support Untranslated Transactions "
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_read_xact_type_armmussidv_armmussid

CHECKSUM: "795023708 3436722686"
ANNOTATION: " Ncore does not support Untranslated Transactions "
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_write_xact_type_awmmusecsid_awmmusid

CHECKSUM: "3043694760 3219442444"
ANNOTATION: " Ncore does not support Untranslated Transactions "
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_write_xact_type_awmmussidv_awmmussid

CHECKSUM: "4158193958 2119673082"
ANNOTATION: " case number:01838233 "
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_arlock_axi4_exclusive

CHECKSUM: "3730288154 1755047066"
ANNOTATION: " case number:01838233 "
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_arlock_axi4_no_exclusive

CHECKSUM: "4080987539 2960192527"
ANNOTATION: " case number:01838233 "
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_awlock_axi4_exclusive

CHECKSUM: "271059912 1801681910"
ANNOTATION: " case number:01838233 "
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_awlock_axi4_no_exclusive

CHECKSUM: "1018574834 3470482598"
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_atomic_xact_type_awburst_awsize
	coveritem "atomic_burst_size"
		ANNOTATION: " Maximum supportable data width for master-4 is 64bit "
		bins "burst_size_128bit"
		ANNOTATION: " Maximum supportable data width for master-4 is 64bit "
		bins "burst_size_256bit"
CHECKSUM: "3374585263 426501806"
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_atomic_xact_type_awsize_awlen
	coveritem "atomic_burst_size"
		ANNOTATION: " Maximum supportable data width for master-4 is 64bit "
		bins "burst_size_256bit"
		ANNOTATION: " Maximum supportable data width for master-4 is 64bit "
		bins "burst_size_128bit"
CHECKSUM: "2799461277 3420475926"
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_atomic_xact_type_awcache_awdomain
	coveritem "cross_atomic_xact_type_awcache_awdomain"
		bins {{"atomic_store_xact"},{"atomic_store_umin","atomic_store_umax","atomic_store_smin","atomic_store_smax","atomic_store_set","atomic_store_eor","atomic_store_clr","atomic_store_add"},{"normal_non_cacheable_bufferable","normal_non_cacheable_non_bufferable"},{"domain_system_shareable","domain_outer_shareable","domain_inner_shareable","domain_non_shareable"}}
		bins {{"atomic_store_xact"},{"atomic_store_umin","atomic_store_umax","atomic_store_smin","atomic_store_smax","atomic_store_set","atomic_store_eor","atomic_store_clr","atomic_store_add"},{"device_bufferable","device_non_bufferable"},{"domain_system_shareable"}}
		bins {{"atomic_load_xact"},{"atomic_load_umin","atomic_load_umax","atomic_load_smin","atomic_load_smax","atomic_load_set","atomic_load_eor","atomic_load_clr","atomic_load_add"},{"normal_non_cacheable_bufferable","normal_non_cacheable_non_bufferable"},{"domain_system_shareable","domain_outer_shareable","domain_inner_shareable","domain_non_shareable"}}
		bins {{"atomic_load_xact"},{"atomic_load_umin","atomic_load_umax","atomic_load_smin","atomic_load_smax","atomic_load_set","atomic_load_eor","atomic_load_clr","atomic_load_add"},{"device_bufferable","device_non_bufferable"},{"domain_system_shareable"}}
		bins {{"atomic_swap_xact"},{"atomic_swap"},{"normal_non_cacheable_bufferable","normal_non_cacheable_non_bufferable"},{"domain_system_shareable","domain_outer_shareable","domain_inner_shareable","domain_non_shareable"}}
		bins {{"atomic_swap_xact"},{"atomic_swap"},{"device_bufferable","device_non_bufferable"},{"domain_system_shareable"}}
		bins {{"atomic_compare_xact"},{"atomic_compare"},{"normal_non_cacheable_bufferable","normal_non_cacheable_non_bufferable"},{"domain_system_shareable","domain_outer_shareable","domain_inner_shareable","domain_non_shareable"}}
		bins {{"atomic_compare_xact"},{"atomic_compare"},{"device_bufferable","device_non_bufferable"},{"domain_system_shareable"}}
CHECKSUM: "1729213596 641094216"
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_atomic_xact_type_bresp_burst_length
	coveritem "cross_atomic_xact_type_bresp_burst_length"
		ANNOTATION: " CONC-16746 "
		bins {{"atomic_store_xact"},{"atomic_store_umin","atomic_store_umax","atomic_store_smin","atomic_store_smax","atomic_store_set","atomic_store_eor","atomic_store_clr","atomic_store_add"},{"decerr_resp","slverr_resp"},{"burst_length[001:040]"}}
CHECKSUM: "2247344608 2194455192"
covergroup unified_prog::svt_axi_port_monitor_amba5_def_cov_callback::trans_cross_atomic_xact_type_endianness
	coveritem "endian_type"
		ANNOTATION: " Ncore does not support big endian mode "
		bins "big_endian"
CHECKSUM: "1475289302 2980798944"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_araddr_arsize_axi4_dwlt_128bit
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_araddr_mid_arsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"addr_range_mid"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "429038432 458051790"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_araddr_arsize_axi4_dwlt_256bit
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_araddr_mid_arsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"addr_range_mid"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "531726752 1475197894"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_araddr_arsize_axi4_dwlt_512bit
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_length"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[081:0c0]"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[0c1:100]"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_araddr_mid_arsize"
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]"},{"addr_range_mid"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "2724749855 1071945082"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_araddr_axi4
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "4281776756 3418442406"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_arsize_axi4_dwlt_128bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_arsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "726289094 1449290466"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_arsize_axi4_dwlt_256bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_arsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "683125029 1147891172"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arlen_arsize_axi4_dwlt_512bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "2675878943 3321374886"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arburst_arqos_axi4
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "234874810 1351104688"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arcache_modifiable_bit_read_unaligned_transfer_axi4_dweq_128bit::SHAPE{Guard_OFF(axi_arcache_modifiable_bit_read_unaligned_transfer_axi4_dweq_128bit.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "3141377486 315064816"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_arcache_modifiable_bit_read_unaligned_transfer_axi4_dweq_64bit::SHAPE{Guard_OFF(axi_arcache_modifiable_bit_read_unaligned_transfer_axi4_dweq_64bit.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "1576636424 3172993324"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_atomictype_rresp_all_axi4
	coveritem "atomic_type"
		ANNOTATION: " Ncore not supported atomic_type lock "
		bins "locked"
CHECKSUM: "849678155 3526494916"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awaddr_awsize_axi4_dwlt_128bit
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_awburst_awlen_awaddr_mid_awsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"addr_range_mid"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "1192651062 2690228988"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awaddr_awsize_axi4_dwlt_256bit
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_awburst_awlen_awaddr_mid_awsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"addr_range_mid"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "2123031684 2072236246"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awaddr_awsize_axi4_dwlt_512bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "3834526052 776346196"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awaddr_axi4
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "2764098070 162024570"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awsize_axi4_dwlt_128bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_awburst_awlen_awsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "3668919587 2287327430"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awsize_axi4_dwlt_256bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_awburst_awlen_awsize"
		ANNOTATION: " Ncore not supported narrow transafer for burst_lenght >1 "
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]","burst_length[081:0c0]","burst_length[0c1:100]"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "705659130 2745544053"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awlen_awsize_axi4_dwlt_512bit
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "4163025149 2395583229"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awburst_awqos_axi4
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "78944187 168939908"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awcache_modifiable_bit_write_unaligned_transfer_axi4_dweq_128bit::SHAPE{Guard_OFF(axi_awcache_modifiable_bit_write_unaligned_transfer_axi4_dweq_128bit.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "846483870 1733773336"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_awcache_modifiable_bit_write_unaligned_transfer_axi4_dweq_64bit::SHAPE{Guard_OFF(axi_awcache_modifiable_bit_write_unaligned_transfer_axi4_dweq_64bit.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "4245574234 996672794"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_read_unaligned_transfer_axi4_dwlt_128bit::SHAPE{Guard_OFF(axi_read_unaligned_transfer.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "3116072326 2752944319"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_read_unaligned_transfer_axi4_dwlt_64bit::SHAPE{Guard_OFF(axi_read_unaligned_transfer.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "2048689917 1668088090"
covergroup "unified_prog::svt_axi_port_monitor_def_cov_callback::trans_cross_axi_write_unaligned_transfer_axi4_dwlt_128bit::SHAPE{Guard_OFF(axi_write_unaligned_transfer.ignore_4k_boundary_cross)}"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
CHECKSUM: "3695483216 3110054152"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_meta_axi_read
	coveritem "ARVALID_to_first_RVALID_Delay"
		ANNOTATION: " Ncore does not support this scenario "
		bins "arvalid_to_first_rvalid_delay_min"
CHECKSUM: "2065416353 4284520671"
covergroup unified_prog::svt_axi_port_monitor_def_cov_callback::trans_meta_axi_write
	coveritem "last_wdata_handshake_to_BVALID_Delay"
		ANNOTATION: " Ncore does not support this scenario "
		bins "last_wdata_handshake_to_bvalid_delay_min"
CHECKSUM: "2894960180 1112088104"
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_araddr
	coveritem "araddr_min_mid_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "araddr_range_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "araddr_range_min"
CHECKSUM: "828570589 1810449160"
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_arburst
	coveritem "arburst"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "svt_axi_transaction_burst_fixed"
CHECKSUM: "4218350733 911055264"
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_awaddr
	coveritem "awaddr_min_mid_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "awaddr_range_max"
		ANNOTATION: " Invalid address range for Ncore "
		bins "awaddr_range_min"
CHECKSUM: "27061133 3483910448"
covergroup unified_prog::svt_axi_port_monitor_def_state_cov_callback#(svt_axi_master_if.svt_axi_monitor_modport)::signal_state_awburst
	coveritem "awburst"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "svt_axi_transaction_burst_fixed"
CHECKSUM: "683125029 1147891172"
covergroup_instance "unified_prog::uvm_test_top.m_concerto_env.snps.svt.amba_system_env.axi_system[0].master[3]_trans_cross_axi_arburst_arlen_arsize_axi4_dwlt_512bit"
	coveritem "burst_length"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[0c1:100]"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[081:0c0]"
	coveritem "burst_type"
		ANNOTATION: " Ncore not supported fixed burst_type "
		bins "fixed_burst"
	coveritem "axi_arburst_arlen_arsize"
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"read_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		bins {{"read_xact"},{"incr_burst"},{"burst_length[041:080]"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "2123031684 2072236246"
covergroup_instance "unified_prog::uvm_test_top.m_concerto_env.snps.svt.amba_system_env.axi_system[0].master[3]_trans_cross_axi_awburst_awlen_awaddr_awsize_axi4_dwlt_512bit"
	coveritem "addr"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_min"
		ANNOTATION: " Invalid address range for Ncore "
		bins "addr_range_max"
	coveritem "burst_length"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[081:0c0]"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[0c1:100]"
	coveritem "axi_awburst_awlen_awaddr_mid_awsize"
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"addr_range_mid"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]"},{"addr_range_mid"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
CHECKSUM: "705659130 2745544053"
covergroup_instance "unified_prog::uvm_test_top.m_concerto_env.snps.svt.amba_system_env.axi_system[0].master[3]_trans_cross_axi_awburst_awlen_awsize_axi4_dwlt_512bit"
	coveritem "burst_length"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[081:0c0]"
		ANNOTATION: " Ncore has a 256-bit data bus for Master-3, so the maximum supported burst length for Master-3 is 128.
 A burst length greater than 128 would exceed the 4 KB boundary. "
		bins "burst_length[0c1:100]"
	coveritem "axi_awburst_awlen_awsize"
		ANNOTATION: " Ncore supports narrow transfer for burst lenght 1 but, wrap burst does not supports burst lenght 1 
So Ncore will not support narrow transfer for wrap burst. "
		bins {{"write_xact"},{"wrap_burst"},{"burst_length[001:040]"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
		bins {{"write_xact"},{"incr_burst"},{"burst_length[041:080]"},{"burst_size_128bit","burst_size_64bit","burst_size_32bit","burst_size_16bit","burst_size_8bit"}}
