

node $WORK_TOP/../scripts/qrsim.js -a -m -q -e dve -c -n hw_config_two -d ASSERT_ON,RTL_DUT,INHOUSE_AXI,INHOUSE_APB_VIP -Z $WORK_TOP/../test_projects/ncore_v3.0_configs/fsys_config/hw_cfg_2
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_bringup_test -q -R 7768131 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+dve_sb_en=1 -u _random_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_bringup_test -q -R 29779756 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+dve_sb_en=1,+enable_error=1 -u _err_injection_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_err_log_en_test -q -R 7759542 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+dve_sb_en=1 -u _err_log_en_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 30463025 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuedr_TransErrDetEn_seq,+inject_dtw_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuedr_TransErrDetEn_DtwtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 47453909 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuedr_TransErrDetEn_seq,+inject_snp_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuedr_TransErrDetEn_SnptargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 23059503 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuedr_TransErrDetEn_seq,+inject_cmd_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuedr_TransErrDetEn_CmdtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 792658 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuedr_TransErrDetEn_seq,+inject_str_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuedr_TransErrDetEn_StrtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 36804713 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuelr_seq,+inject_dtw_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuelr_TransErrDetEn_DtwtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 63671501 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuelr_seq,+inject_snp_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuelr_TransErrDetEn_SnptargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 8307894 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuelr_seq,+inject_cmd_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuelr_TransErrDetEn_CmdtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 48117124 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuelr_seq,+inject_str_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuelr_TransErrDetEn_StrtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 40419287 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveueir_TransErrInt_seq,+inject_dtw_trgt_id_err=1,+k_num_requests=10 -u _csr_dveueir_TransErrInt_DtwtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 25935188 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveueir_TransErrInt_seq,+inject_snp_trgt_id_err=1,+k_num_requests=10 -u _csr_dveueir_TransErrInt_SnptargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 51929624 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveueir_TransErrInt_seq,+inject_cmd_trgt_id_err=1,+k_num_requests=10 -u _csr_dveueir_TransErrInt_CmdtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 40516442 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveueir_TransErrInt_seq,+inject_str_trgt_id_err=1,+k_num_requests=10 -u _csr_dveueir_TransErrInt_StrtargtId_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_targt_id_err_test -q -R 24999492 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=dve_csr_dveuedr_noDetEn_seq,+inject_str_trgt_id_err=1,+k_num_requests=10 -u _csr_dveuedr_noDetEn_uncorr_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_snpcap_ral_test -q -R 6401931 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_num_requests=100 -u _csr_dveuser_SnoopCap_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_ral_test -q -R 18861613 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=uvm_reg_hw_reset_seq -u _csr_hw_reset_0
node $WORK_TOP/../scripts/qrsim.js -e dve -n hw_config_two -t dve_ral_test -q -R 46490748 -p +UVM_MAX_QUIT_COUNT=1,+UVM_VERBOSITY=UVM_NONE,+UVM_TIMEOUT=1000000000000,+k_targ_src_id_chk_en=1,+k_csr_seq=uvm_reg_bit_bash_seq -u _csr_bit_bash_0
