class chi_subsys_noncoh_seq extends svt_chi_rn_coherent_transaction_base_sequence;

  typedef bit [(`SVT_CHI_MAX_DATA_WIDTH-1):0] store_data_type;
  store_data_type store_data, directed_store_data;

  /** 
   * Indicates that the data provided in directed_data_mailbox should be used
   * for the transactions generated by this sequence
   */
  bit randomize_with_directed_data;
  rand svt_chi_transaction::order_type_enum seq_order_type = svt_chi_transaction::REQ_EP_ORDERING_REQUIRED;
  rand bit seq_mem_attr_is_early_wr_ack_allowed = 0;
  rand bit seq_mem_attr_mem_type = 1;
  bit k_decode_err_illegal_acc_format_test_unsupported_size = 0; 
  bit datasize_8bytes_or_16bytes = 1;

  /**
   * Applicable if randomize_with_directed_data is set.
   * A mailbox into which a user can put data to which transactions have to be
   * generated.
   */
  mailbox #(store_data_type) directed_data_mailbox;
  
  `svt_xvm_object_utils(chi_subsys_noncoh_seq)
  `svt_xvm_declare_p_sequencer(svt_chi_rn_transaction_sequencer)

  function new(string name = "chi_subsys_noncoh_seq");
    super.new(name);
    directed_data_mailbox=new();
  endfunction // new

    /** 
    * This sequence randomizes a single transaction based on the weights assigned.
    *  - If randomized_with_directed_addr is set, the transaction is randomized with
    *    the address specified in directed_addr
    *  - If randomized_with_directed_data is set, the transaction is randomized with
    *    the data specified in directed_store_data
    *  - If store_data is set, the transaction is randomized with
    *    the data specified in store_data
    *  .
    */
  virtual task randomize_xact(svt_chi_rn_transaction           rn_xact,
                              bit                              randomize_with_directed_addr, 
                              bit[`SVT_CHI_MAX_ADDR_WIDTH-1:0] directed_addr,
                              bit                              directed_snp_attr_is_snoopable,
                              svt_chi_common_transaction::snp_attr_snp_domain_type_enum directed_snp_attr_snp_domain_type,
                              bit                              directed_mem_attr_allocate_hint,
                              bit                              directed_is_non_secure_access,
                              bit                              directed_allocate_in_cache,
                              svt_chi_common_transaction::data_size_enum directed_data_size, 
                              bit [(`SVT_CHI_MAX_DATA_WIDTH-1):0] directed_data,
                              bit [(`SVT_CHI_MAX_BE_WIDTH-1):0] directed_byte_enable,
                              output bit                       req_success,
                              input  int                       sequence_index = 0,
                              input  bit                       gen_uniq_txn_id = 0);
    
    `svt_debug("randomize_xact", "chi_subsys_noncoh_seq - Entered ");

    // Get config from corresponding sequencer and assign it here.
    rn_xact.cfg      = node_cfg;
    if (randomize_with_directed_data)begin
      void'(directed_data_mailbox.try_get(directed_store_data));
    end
    
    req_success = rn_xact.randomize() with 
    { 
    mem_attr_is_early_wr_ack_allowed == seq_mem_attr_is_early_wr_ack_allowed;
    mem_attr_mem_type  == seq_mem_attr_mem_type;
    order_type == seq_order_type;
    xact_type dist {
                    svt_chi_common_transaction::READNOSNP       := readnosnp_wt,       
                    svt_chi_common_transaction::WRITENOSNPFULL  := writenosnpfull_wt,  
                    svt_chi_common_transaction::WRITENOSNPPTL   := writenosnpptl_wt   
                    };
    
    if (randomize_with_directed_addr)  addr == directed_addr;
    // `ifdef SVT_CHI_ISSUE_A_ENABLE
      if (randomize_with_directed_addr && directed_snp_attr_is_snoopable && use_directed_snp_attr)  snp_attr_snp_domain_type == directed_snp_attr_snp_domain_type;
    // `endif
    if (randomize_with_directed_addr && use_directed_mem_attr)  mem_attr_allocate_hint == directed_mem_attr_allocate_hint;
    if (randomize_with_directed_addr && use_directed_non_secure_access)  is_non_secure_access == directed_is_non_secure_access;
    
    requires_go_before_barrier == 1;

    if(store_data != 0) data == store_data;
    if (randomize_with_directed_data)  data == directed_store_data;


    data_size == (k_decode_err_illegal_acc_format_test_unsupported_size==0) ? svt_chi_rn_transaction::SIZE_4BYTE : svt_chi_rn_transaction::SIZE_8BYTE;

    mem_attr_is_cacheable == 0;
    byte_enable == 'hF;
    if(xact_type==svt_chi_common_transaction::WRITENOSNPPTL) {
        is_writedatacancel_used_for_write_xact == 0;
    }
    // `endif
    };
    void'($value$plusargs("datasize_8bytes=%0b",datasize_8bytes_or_16bytes));
    rn_xact.data_size = (k_decode_err_illegal_acc_format_test_unsupported_size==0) ? svt_chi_rn_transaction::SIZE_4BYTE : ((datasize_8bytes_or_16bytes==1) ? svt_chi_rn_transaction::SIZE_8BYTE : svt_chi_rn_transaction::SIZE_16BYTE);
    rn_xact.data      = (randomize_with_directed_data==1) ? directed_store_data : rn_xact.data;
    rn_xact.byte_enable = 'hF;

    `svt_debug("randomize_xact", $sformatf("chi_subsys_noncoh_seq - After randomization, randomize_xact \nrandomize_with_directed_addr %0b directed_addr %0h directed_snp_attr_is_snoopable %0b directed_snp_attr_snp_domain_type %0s directed_mem_attr_allocate_hint %0b directed_is_non_secure_access %0b directed_allocate_in_cache %0b directed_data_size %0s directed_data %0h directed_byte_enable %0h req_success %0b sequence_index %0b gen_uniq_txn_id %0b directed_store_data %0h randomize_with_directed_data %0b store_data %0h data_size %0s xact_type %0s byte_enable %0h data %0h",randomize_with_directed_addr, directed_addr, directed_snp_attr_is_snoopable, directed_snp_attr_snp_domain_type.name, directed_mem_attr_allocate_hint, directed_is_non_secure_access, directed_allocate_in_cache, directed_data_size.name, directed_data, directed_byte_enable, req_success, sequence_index, gen_uniq_txn_id, directed_store_data,randomize_with_directed_data,store_data,rn_xact.data_size.name,rn_xact.xact_type.name,rn_xact.byte_enable,rn_xact.data));
  
    //rn_xact.addr[5:0] = 'h0;
    store_data = 'h0;
    `svt_debug("randomize_xact",$psprintf("chi_subsys_noncoh_seq req_success - %b \n%0s", req_success, rn_xact.sprint()));
  endtask // randomize_xact
  
  virtual task body();
    if((readnosnp_wt+writenosnpfull_wt+writenosnpptl_wt) == 0)
      `svt_fatal("body","Wight should be non zero value for atleast one Non-Coherent transaction (READNOSNP, WRITENOSNPPTL, WRITENOSNPFULL)");
    super.body();
  endtask // body

  virtual function svt_chi_rn_transaction get_xact_from_active_queue(int unsigned index);
    if(index > active_xacts.size())
      get_xact_from_active_queue = null;
    else
      get_xact_from_active_queue = active_xacts[index];
  endfunction // get_xact_from_active_queue
  
endclass: chi_subsys_noncoh_seq
