#!/usr/bin/perl 

sub parallel{ # name, cmd, num

    $cmd = $_[0];

    select (undef, undef, undef, 0.1);
    sleep(1);
    print("Starting: $cmd\n");

    my $pid = fork;
    if (!defined $pid) { 
        die ("Cannot Fork!") 
    };
    if ($pid == 0) {
        open ($fh, "|$cmd");
        while (my $line=<$fh>) {
            print $line;
        }
        close ($fh);
        exit 0;
    }
    return $pid;
}

my $num = 0;

my @tests = (
    "cd ../dce/tb ; ./runtestp_bamboo",
    "cd ../dmi/tb ; ./runtestp_bamboo",
    "cd ../aiu/tb ; ./runtestp_bamboo",
    "cd ../sub_sys/tb ; ./runtestp_bamboo"
    );

my @pids;
foreach $t (@tests) {
    push @pids, parallel($t);
    sleep(1);
    $num = $num + 1;
}

foreach $p (@pids) {
    waitpid $p, 0;
}
print ("runtestp/top done.");
exit 0;
