#!/bin/bash -fx
if [ -z $WORK_TOP ]; 
then
    echo "WORK_TOP is not set"
    exit 1
fi
export ARTERISD_LICENSE_FILE=5281@lic-node0.arteris.com
export PATH="/engr/dev/releases/maestro/build/releases/Ncore_3.2.0_RC4/bin:/engr/dev/releases/maestro/build/releases/Ncore_3.2.0_RC4/maestro-server:${PATH}"
export MAESTRO_TCLLIB=/engr/dev/releases/maestro/build/releases/Ncore_3.2.0_RC4/maestro-doc/examples/tcllib

source $WORK_TOP/dv/scripts/setup_ncore320_RC4_repos
