//==================================================
// This file contains the Excluded objects
// Generated By User: hsajja
// Format Version: 2
// Date: Mon Feb 24 18:30:19 2025
// ExclMode: default
//==================================================
CHECKSUM: "3361674674 1503535432"
covergroup unified_prog::ioaiu_coverage::perity_error_covergroup

CHECKSUM: "2454881129 1"
covergroup unified_prog::ioaiu_coverage::smi_pkt

CHECKSUM: "463436860 3646034747"
covergroup unified_prog::ioaiu_coverage::sys_req_events_cg

CHECKSUM: "2863361138 3800724827"
covergroup unified_prog::ioaiu_coverage::uncorrectable_error_covergroup_core0
	coveritem "smi_prot_corr_error_info"
	coveritem "smi_prot_corr_error_type"
	coveritem "sys_event_time_out_error_info"
	coveritem "sys_event_time_out_error_type"
	coveritem "sys_event_time_out_error"
CHECKSUM: "1926321422 4168073200"
covergroup unified_prog::smi_resiliency_coverage::smi_transaction_resiliency
	coveritem "cross_of_DtwReqMsg_type_and_ndp_parity_error"
	coveritem "cross_of_DtwReqMsg_type_and_dp_parity_error"
CHECKSUM: "3344064751 299193501"
covergroup unified_prog::trace_trigger_utils::cg_trigger
	coveritem "cp_sets_native_matched"
CHECKSUM: "817283382 3726136149"
covergroup unified_prog::ioaiu_coverage::axi4_rd_addr_chnl_core0
	coveritem "cx_coh_norncnonbuf_wide_txn"
		bins {{"size_3_align_offset_18"},{"incr_arlen_09"}}
		bins {{"size_3_align_offset_28"},{"incr_arlen_255"}}
		bins {{"size_3_align_offset_08"},{"incr_arlen_255"}}
		bins {{"size_3_align_offset_38"},{"incr_arlen_02"}}
	coveritem "cx_coh_wtralloc_wide_txn"
		bins {{"size_3_align_offset_08"},{"incr_arlen_00"}}
		bins {{"size_3_align_offset_38"},{"incr_arlen_05"}}
		bins {{"size_3_align_offset_38"},{"incr_arlen_01"}}
	coveritem "cx_coh_wtrwalloc_wide_txn"
		bins {{"size_3_align_offset_38"},{"incr_arlen_09"}}
	coveritem "cx_noncoh_devnonbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_arlen_0f"},{"dii_tgt"}}
	coveritem "cx_noncoh_devbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_arlen_0f"},{"dii_tgt"}}
	coveritem "cx_noncoh_norncnonbuf_wide_txn"
		bins {{"size_3_align_offset_38"},{"incr_arlen_02","incr_arlen_03"},{"dmi_tgt"}}
CHECKSUM: "329011702 916367130"
covergroup unified_prog::cov_perf_cnt
	coveritem "count_event_first_bins"
		bins "Agent_event_counter_bins"
	coveritem "count_event_second_bins"
		bins "Agent_event_counter_bins"
CHECKSUM: "432038823 1339093954"
covergroup unified_prog::cov_perf_cnt_evt_xCNTVR
	coveritem "count_event_evt_bins"
		bins "Agent_event_counter_bins"
	coveritem "perf_evt_X_counter_value_bins"
		bins {{"Cache_no_ways_to_allocate_bins"},{"other_values","xcntvr_6_10"}}
		bins {{"Cache_eviction_bins","Cache_snoop_hit_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Cache_replay_bins","Cache_write_stall_bins"},{"other_values","xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Cache_read_stall_bins"},{"xcntvr_1_5"}}
		bins {{"Cache_fill_stall_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Number_of_QoS_Starvations_bins"},{"xcntvr_6_10"}}
		bins {{"Cache_snoop_miss_bins","Cache_write_miss_bins","Cache_read_miss_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Div_16_counter_bins","Noc_event_counter_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Agent_event_counter_bins"},{"other_values","xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Captured_SMI_packets_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Active_OTT_entries_bins"},{"other_values","xcntvr_6_10","xcntvr_1_5"}}
		bins {{"SnpRsp_bins","CmdReqRd_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"ACE_Lite_AXI_AR_stall_event_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"ACE_Lite_AXI_W_stall_event_bins","ACE_Lite_AXI_AW_stall_event_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"SMI_2_Rx_Stall_event_bins","SMI_1_Rx_Stall_event_bins","SMI_0_Rx_Stall_event_bins"},{"other_values","xcntvr_6_10"}}
		bins {{"SMI_2_Tx_Stall_event_bins"},{"xcntvr_6_10"}}
CHECKSUM: "3830194836 2400954175"
covergroup unified_prog::ioaiu_coverage::axi4_wr_addr_chnl_core0
	coveritem "cx_coh_norncnonbuf_wide_txn"
		bins {{"size_3_align_offset_38"},{"incr_awlen_16_47"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03","incr_awlen_04","incr_awlen_05","incr_awlen_06","incr_awlen_07","incr_awlen_08","incr_awlen_09","incr_awlen_0a","incr_awlen_0b","incr_awlen_0c","incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03","incr_awlen_04","incr_awlen_05","incr_awlen_06","incr_awlen_07"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_176_207"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_09"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_0b","incr_awlen_0c","incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_00","incr_awlen_01","incr_awlen_02"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_04","incr_awlen_05","incr_awlen_06","incr_awlen_07"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_09","incr_awlen_0a","incr_awlen_0b"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_208_254"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_06"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_09","incr_awlen_0a","incr_awlen_0b","incr_awlen_0c","incr_awlen_0d"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03"}}
	coveritem "cx_coh_wtralloc_wide_txn"
		bins {{"size_3_align_offset_08"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_128_143"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_127"}}
	coveritem "cx_coh_wtwalloc_wide_txn"
		bins {{"size_3_align_offset_38"},{"incr_awlen_128_143"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_0c","incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_0c","incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_06","incr_awlen_07","incr_awlen_08","incr_awlen_09","incr_awlen_0a"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_255","incr_awlen_208_254"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_01"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_0a","incr_awlen_0b"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_0f"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_03"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_0a"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_128_143","incr_awlen_127"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03","incr_awlen_04","incr_awlen_05","incr_awlen_06","incr_awlen_07","incr_awlen_08"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_02","incr_awlen_03"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03","incr_awlen_04","incr_awlen_05"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_09","incr_awlen_0a","incr_awlen_0b","incr_awlen_0c","incr_awlen_0d","incr_awlen_0e"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_07"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_05","incr_awlen_06","incr_awlen_07"}}
	coveritem "cx_coh_wtrwalloc_wide_txn"
		bins {{"size_3_align_offset_08"},{"incr_awlen_176_207"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_176_207"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_128_143"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_208_254"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_07","incr_awlen_08","incr_awlen_09"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_0f"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_01"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_03","incr_awlen_04"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_0a"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_0b","incr_awlen_0c"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_02","incr_awlen_03"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_07"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_05"}}
		bins {{"size_3_align_offset_28"},{"incr_awlen_255"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_06","incr_awlen_07"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_02"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_04"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_0d","incr_awlen_0e","incr_awlen_0f"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_01","incr_awlen_02","incr_awlen_03","incr_awlen_04","incr_awlen_05"}}
		bins {{"size_3_align_offset_38"},{"incr_awlen_128_143","incr_awlen_127"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_127"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_08"}}
		bins {{"size_3_align_offset_08"},{"incr_awlen_0a","incr_awlen_0b"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_0b"}}
		bins {{"size_3_align_offset_18"},{"incr_awlen_0e","incr_awlen_0f"}}
	coveritem "cx_noncoh_devnonbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_awlen_0f"},{"dii_tgt"}}
	coveritem "cx_noncoh_devbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_awlen_0f"},{"dii_tgt"}}
	coveritem "cx_noncoh_norncnonbuf_wide_txn"
		bins {{"size_3_align_offset_08"},{"incr_awlen_09"},{"dii_tgt"}}
	coveritem "cx_noncoh_wtwalloc_wide_txn"
		bins {{"size_3_align_offset_28"},{"incr_awlen_0c"},{"dii_tgt"}}
CHECKSUM: "3214418871 1169866178"
covergroup unified_prog::ioaiu_coverage::ccp_coh_noncoh_ops_cg_core0
	coveritem "cx_noncoh_ptl_read_dmi_tgt"
		bins {{"Read"},{"na_arcache_0011","na_arcache_0010"},{"PtlRd"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
		bins {{"Read"},{"na_arcache_0011","na_arcache_0010"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
	coveritem "cx_noncoh_ptl_read_dii_tgt"
		bins {{"Read"},{"na_arcache_0011"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0001","na_arcache_0000"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0010"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0001","na_arcache_0000"},{"PtlRd"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0011"},{"PtlRd"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
	coveritem "cx_coh_ptl_read"
		bins {{"Read"},{"na_arcache_0011"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0011"},{"PtlRd"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"PtlRd"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"PtlRd"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"PtlRd"},{"curr_state_SD"},{"next_state_SD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"PtlRd"},{"curr_state_SC"},{"next_state_SC"},{"CmdNOMsg"},{"coh"}}
	coveritem "cx_noncoh_full_read_dmi_tgt"
		bins {{"Read"},{"na_arcache_0011","na_arcache_0010"},{"FullRr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
		bins {{"Read"},{"na_arcache_0011","na_arcache_0010"},{"FullRr"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
	coveritem "cx_noncoh_full_read_dii_tgt"
		bins {{"Read"},{"na_arcache_0011"},{"FullRr"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0011"},{"FullRr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0010"},{"FullRr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0001","na_arcache_0000"},{"FullRr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Read"},{"na_arcache_0001","na_arcache_0000"},{"FullRr"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
	coveritem "cx_coh_full_read"
		bins {{"Read"},{"na_arcache_0011"},{"FullRr"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"FullRr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"FullRr"},{"curr_state_UC"},{"next_state_UC"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"FullRr"},{"curr_state_SC"},{"next_state_SC"},{"CmdNOMsg"},{"coh"}}
		bins {{"Read"},{"na_arcache_0010"},{"FullRr"},{"curr_state_SD"},{"next_state_SD"},{"CmdNOMsg"},{"coh"}}
	coveritem "cx_noncoh_ptl_write_dmi_tgt"
		bins {{"Write"},{"na_awcache_0010"},{"PtlWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
	coveritem "cx_noncoh_ptl_write_dii_tgt"
		bins {{"Write"},{"na_awcache_0001","na_awcache_0000"},{"PtlWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
	coveritem "cx_coh_ptl_write"
		bins {{"Write"},{"na_awcache_0010"},{"PtlWr"},{"curr_state_UD","curr_state_UC"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Write"},{"na_awcache_0010"},{"PtlWr"},{"curr_state_SD"},{"next_state_UD"},{"CmdRdUnq"},{"coh"}}
	coveritem "cx_noncoh_full_write_dmi_tgt"
		bins {{"Write"},{"na_awcache_0011","na_awcache_0010"},{"FullWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dmi_tgt"}}
	coveritem "cx_noncoh_full_write_dii_tgt"
		bins {{"Write"},{"na_awcache_0010","na_awcache_0001"},{"FullWr"},{"curr_state_UD","curr_state_UC"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Write"},{"na_awcache_0000"},{"FullWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
		bins {{"Write"},{"na_awcache_0011"},{"FullWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"noncoh"},{"dii_tgt"}}
	coveritem "cx_coh_full_write"
		bins {{"Write"},{"na_awcache_0011"},{"FullWr"},{"curr_state_UD"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Write"},{"na_awcache_0010"},{"FullWr"},{"curr_state_UD","curr_state_UC"},{"next_state_UD"},{"CmdNOMsg"},{"coh"}}
		bins {{"Write"},{"na_awcache_0010"},{"FullWr"},{"curr_state_SD","curr_state_SC"},{"next_state_UD"},{"CmdMkUnq"},{"coh"}}
CHECKSUM: "3407418097 2936095403"
covergroup unified_prog::ioaiu_coverage::ccp_ctrl_pkt_core0
	coveritem "b2b_alloc_txns_same_addr"
		bins auto[0]
	coveritem "b2b_alloc_txns_same_index"
		bins auto[1]
	coveritem "nack_ce"
		bins auto[1]
CHECKSUM: "3447192951 445085247"
covergroup unified_prog::ioaiu_coverage::ccp_state_cmdreq_core0
	coveritem "ccp_current_state_vcs"
		bins "UC"
	coveritem "cross_IOC_cmdreqXccpStatesXdtrType"
		bins "CmdMkUnq_SC_UD"
		bins "CmdMkUnq_SD_UD"
		bins "CmdMkUnq_IX_UD"
CHECKSUM: "3899738407 3357601763"
covergroup unified_prog::ioaiu_coverage::ccp_state_snprsp_core0
	coveritem "cross_IOC_SnpRespTypeXccpStatesXcmstatus"
		bins {{"SnpReqMsgType_SnpNoSDInt"},{"SC"},{"SC"},{"SnpRspCmStatus_RV_RS_DC_DTAiu_DTDmi_18"}}
		bins {{"SnpReqMsgType_SnpVldDtr","SnpReqMsgType_SnpNITC","SnpReqMsgType_SnpClnDtr"},{"SC"},{"SC"},{"SnpRspCmStatus_RV_RS_DC_DTAiu_DTDmi_18"}}
CHECKSUM: "3593049554 2437736538"
covergroup unified_prog::ioaiu_coverage::dtreq_cmstatus_err_covergroup_core0
	coveritem "dtrreq_cmstatus_err_covergroup_core"
		bins {{"is_partial_0"},{"dbad_all_one"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_all_zero"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_data_err"}}
CHECKSUM: "3736229596 4279706695"
covergroup unified_prog::ioaiu_coverage::dtwrsp_cmstatus_err_covergroup_core0
	coveritem "dtwrsp_cmstatus_err_covergroup_core"
		bins {{"dtw_rsp_with_data_err","dtw_rsp_with_add_err"},{"ismultiline_1"},{"is_IoCacheEvict"}}
CHECKSUM: "1157330892 3199232278"
covergroup unified_prog::ioaiu_coverage::mission_fault_causes_cg
	coveritem "time_out_error_cp_X_mission_fault_X_time_out_det_en"
		bins {{"sys_req_timeout"},{"mission_fault"},{"time_out_det_en_0"}}
CHECKSUM: "1594167790 3622102429"
covergroup unified_prog::ioaiu_coverage::slv_error_covergroup_core0
	coveritem "slv_error_covergroup_core"
		bins {{"errtype_data_uncorrectable_error"},{"ismultiline_1"},{"slverr"},{"noncoh_read"}}
CHECKSUM: "2330034207 2725953607"
covergroup unified_prog::ioaiu_coverage::smi_StrReq_pkt
	coveritem "coverpoint_StrReq_cmstatus_state"
		bins "State_Sharer"
		bins "State_Unique"
CHECKSUM: "2863361138 3800724827"
covergroup unified_prog::ioaiu_coverage::uncorrectable_error_covergroup_core0
	coveritem "normal_time_out_error_info_cmd_type"
		bins "cmd_type_cmo_dataless"
	coveritem "smi_prot_cmd_types"
		bins "auto_is_bad_smi_prot_cmd_type"
		bins "auto_is_CmpRsp"
	coveritem "sysco_time_out_error_type"
		bins "sysco_event_time_out_err_type"
	coveritem "smi_prot_uncorr_err"
		bins {{"smi_prot_uesr_err_type"},{"smi_prot_uesr_err_info"},{"auto_is_CmpRsp"}}
		bins {{"smi_prot_uesr_err_type"},{"smi_prot_uesr_err_info"},{"auto_is_bad_smi_prot_cmd_type"}}
	coveritem "normal_time_out_error"
		bins {{"erro_type"},{"cmd_type_cmo_dataless"}}
CHECKSUM: "3344064751 299193501"
covergroup unified_prog::trace_trigger_utils::cg_trigger
	coveritem "cp_native_trig_dii_hui_nunitid"
		bins "dii_hui_nunitid_01"
		bins "dii_hui_nunitid_02"
	coveritem "cp_native_trig_dmi_hui_mig"
		bins "dmi_hui_mig_02"
		bins "dmi_hui_mig_01"
