#!/bin/csh

rm -rf ../../../debug/dce/syn
node ../../../dv/scripts/rsim.js -m -e dce -ad RTL_DUT -s ../../../dv/common/config/dce/dce_config1AchlParams.js -n syn
make clean
make dc TCL=dce FILELIST=../../../../debug/dce/syn/rtl/top.f TECHNODE=CLN16FFPLUS LIBRARY=tcbn16ffplusglbwp16p90 REVISION=100a FFCORNER=ffgnp0p88vm40c SSCORNER=ssgnp0p72v125c WIRELOAD=topo SCAN=no COMPILE=yes PERIOD=0.800

