//==================================================
// This file contains the Excluded objects
// Generated By User: hsajja
// Format Version: 2
// Date: Fri Feb 21 10:51:07 2025
// ExclMode: default
//==================================================
CHECKSUM: "426044772 3848751912"
covergroup unified_prog::ioaiu_coverage::perity_error_covergroup

CHECKSUM: "2454881129 1"
covergroup unified_prog::ioaiu_coverage::smi_pkt

CHECKSUM: "1901585065 2400954175"
covergroup unified_prog::ioaiu_coverage::axi5_wr_addr_chnl_core0
	coveritem "cx_noncoh_devnonbuf_wide_txn"
	coveritem "cx_noncoh_devbuf_wide_txn"
CHECKSUM: "3117157264 3597234877"
covergroup unified_prog::ioaiu_coverage::uncorrectable_error_covergroup_core0
	coveritem "smi_prot_corr_error_info"
	coveritem "smi_prot_corr_error_info"
	coveritem "smi_prot_corr_error_type"
	coveritem "smi_prot_uncorr_error_info"
CHECKSUM: "3523296014 3768772543"
covergroup unified_prog::trace_trigger_utils::cg_trigger
	coveritem "cp_TBAR_0_addr_51_12"
	coveritem "cp_TBAR_1_addr_51_12"
	coveritem "cp_TBAR_2_addr_51_12"
	coveritem "cp_TBAR_3_addr_51_12"
	coveritem "cp_native_trig_dii_hui_nunitid"
	coveritem "cp_native_trig_dmi_hui_mig"
	coveritem "cp_sets_native_matched"
CHECKSUM: "1546412345 3726136149"
covergroup unified_prog::ioaiu_coverage::axi5_rd_addr_chnl_core0
	coveritem "cx_noncoh_devnonbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_arlen_0f"},{"dii_tgt"}}
	coveritem "cx_noncoh_devbuf_wide_txn"
		bins {{"size_3_align_offset_38","size_3_align_offset_30","size_3_align_offset_28","size_3_align_offset_20","size_3_align_offset_18","size_3_align_offset_10","size_3_align_offset_08","size_3_align_offset_00"},{"wrap_arlen_0f"},{"dii_tgt"}}
CHECKSUM: "329011702 2980176424"
covergroup unified_prog::cov_perf_cnt
	coveritem "count_event_first_bins"
		bins "Noc_event_counter_bins"
	coveritem "count_event_second_bins"
		bins "Noc_event_counter_bins"
CHECKSUM: "432038823 629676074"
covergroup unified_prog::cov_perf_cnt_evt_xCNTVR
	coveritem "count_event_evt_bins"
		bins "Noc_event_counter_bins"
		bins "SnpRsp_bins"
		bins "Agent_event_counter_bins"
	coveritem "perf_evt_X_counter_value_bins"
		bins {{"Number_of_QoS_Starvations_bins"},{"other_values","xcntvr_6_10"}}
		bins {{"Div_16_counter_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Dropped_SMI_packets_bins"},{"xcntvr_6_10"}}
		bins {{"Captured_SMI_packets_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"Active_OTT_entries_bins"},{"other_values","xcntvr_6_10","xcntvr_1_5"}}
		bins {{"CmdReqRd_bins"},{"xcntvr_6_10"}}
		bins {{"ACE_Lite_AXI_AR_stall_event_bins"},{"xcntvr_6_10"}}
		bins {{"ACE_Lite_AXI_AW_stall_event_bins"},{"xcntvr_6_10","xcntvr_1_5"}}
		bins {{"SMI_2_Rx_Stall_event_bins","SMI_1_Rx_Stall_event_bins","SMI_0_Rx_Stall_event_bins"},{"other_values","xcntvr_6_10"}}
CHECKSUM: "3843353348 1135340446"
covergroup unified_prog::ioaiu_coverage::dec_error_covergroup_core0
	coveritem "dec_error_covergroup_core"
		bins {{"errtype_illegalCoherentDIIAccess"},{"ismultiline_0"},{"decerr"},{"noncoh_atomic","coh_atomic"}}
		bins {{"errtype_illegalCoherentDIIAccess"},{"ismultiline_0"},{"decerr"},{"coh_write"}}
		bins {{"errtype_addrNotInMemRegion"},{"ismultiline_0"},{"decerr"},{"noncoh_atomic"}}
CHECKSUM: "1567739264 217770381"
covergroup unified_prog::ioaiu_coverage::dtreq_cmstatus_err_covergroup_core0
	coveritem "is_dp_dbad"
		bins "dbad_all_zero"
	coveritem "is_dp_dbad"
		bins "dbad_all_zero"
	coveritem "dtrreq_cmstatus_err_covergroup_core"
		bins {{"is_partial_1"},{"dbad_all_one"},{"is_read"},{"ismultiline_1","ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_all_one"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_all_zero"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_data_err","dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_7"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_7"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_6"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_6"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_5"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_5"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_4"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_4"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_3"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_3"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_2"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_2"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_1"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_1"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_0"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_1"},{"dbad_0"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_7"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_7"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_6"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_6"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_5"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_5"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_4"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_4"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_3"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_3"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_2"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_2"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_1"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_1"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_0"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_0"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_all_one"},{"is_read"},{"ismultiline_1"},{"dtr_req_with_add_err"}}
	coveritem "dtrreq_cmstatus_err_covergroup_core"
		bins {{"is_partial_1"},{"dbad_7","dbad_6","dbad_5","dbad_4","dbad_3","dbad_2","dbad_1","dbad_0","dbad_all_one"},{"is_read"},{"ismultiline_1","ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_7","dbad_6","dbad_5","dbad_4","dbad_3","dbad_2","dbad_1","dbad_0","dbad_all_one"},{"is_read"},{"ismultiline_1","ismultiline_0"},{"dtr_req_with_add_err"}}
		bins {{"is_partial_0"},{"dbad_all_zero"},{"is_read"},{"ismultiline_0"},{"dtr_req_with_data_err","dtr_req_with_add_err"}}
CHECKSUM: "2330034207 2725953607"
covergroup unified_prog::ioaiu_coverage::smi_StrReq_pkt
	coveritem "coverpoint_StrReq_cmstatus_state"
		bins "State_Sharer"
		bins "State_Unique"
CHECKSUM: "3117157264 3597234877"
covergroup unified_prog::ioaiu_coverage::uncorrectable_error_covergroup_core0
	coveritem "normal_time_out_error_info_cmd_type"
		bins "cmd_type_cmo_dataless"
CHECKSUM: "3523296014 3768772543"
covergroup unified_prog::trace_trigger_utils::cg_trigger
	coveritem "cp_native_trig_dii_hui_nunitid"
		bins "dii_hui_nunitid_02"
	coveritem "cp_native_trig_dmi_hui_mig"
		bins "dmi_hui_mig_02"
	coveritem "cp_sets_traceme"
		bins auto[15]
